### ISSUE TITLE
编译时出现如下错误

### ISSUE THREAD

**Issue by jian-android** [Spxg/android_device_samsung_i959#2]
make: *** 没有规则可以创建“/home/jian/los/out/target/product/i959/obj/EXECUTABLES/healthd_intermediates/import_includes”需要的目标“/home/jian/los/out/target/product/i959/obj/STATIC_LIBRARIES/libminui_intermediates/export_includes”。 停止。 

本人菜鸡 望大神告知！

**Comment by Spxg** [comment]
将broadconfig.mk 中 RECOVERY_VARIANT := twrp 注释

**Comment by jian-android** [comment]
注释依旧不行 不知道是我问题吗23333

**Comment by Spxg** [comment]
14.1已基本完美，请移步到github.com/exynos5410

**Comment by SUNYUMI** [comment]
BOARD_HAS_DOWNLOAD_MODE := true
删除此指令

**Comment by j1ans** [comment]
> BOARD_HAS_DOWNLOAD_MODE := true 删除此指令

谢谢。当年已解决。
